# Programming Assignment No :- 8

<b> Question No. 1<b> :- Write a Python Program to Add Two Matrices?

In [12]:
x = [[1,2,3],
    [4,5,6],
    [7,8,9]]

y = [[1,2,3],
    [4,5,6],
    [7,8,9]]

output = [[0,0,0],
         [0,0,0],
         [0,0,0]]


for i in range(len(x)):  
# iterate through columns
    for j in range(len(x[0])):
        output[i][j] = x[i][j] + y[i][j]
        
for r in output:
    print(r)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [30]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

y = np.array ([[1,2,3],[4,5,6],[7,8,9]])

output = np.add(x,y)

print(" First Matrix is \n{} \n Second Matrix is \n{} \nOutput is \n{}".format(x,y,output))

 First Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Second Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
Output is 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


<b> Question No. 2<b> :-Write a Python Program to Multiply Two Matrices?

In [32]:
x = [[1,2,3],
    [4,5,6],
    [7,8,9]]

y = [[1,2,3],
    [4,5,6],
    [7,8,9]]

output = [[0,0,0],
         [0,0,0],
         [0,0,0]]


for i in range(len(x)):  
# iterate through columns
    for j in range(len(x[0])):
        output[i][j] = x[i][j] * y[i][j]
        
for r in output:
    print(r)

[1, 4, 9]
[16, 25, 36]
[49, 64, 81]


In [34]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

y = np.array ([[1,2,3],[4,5,6],[7,8,9]])

output = np.multiply(x,y)

print(" First Matrix is \n{} \n Second Matrix is \n{} \nOutput is \n{}".format(x,y,output))

 First Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Second Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
Output is 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


<b> Question No. 3<b> :-Write a Python Program to Transpose a Matrix?

In [40]:
A = [[1,2,3],
     [4,5,6]]
C = [[0,0],
     [0,0],
     [0,0]]
     
for i in range(len(A)):
    for j in range(len(A[0])):
        C[j][i] = A[i][j]
print(C)

[[1, 4], [2, 5], [3, 6]]


In [52]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

output = np.transpose(x)

print("Input matrix is \n{} \nTranspose Matrix is \n{}".format(x,output))


Input matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
Transpose Matrix is 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<b> Question No. 4<b> :-Write a Python Program to Sort Words in Alphabetic Order?

In [55]:
str_words = input("Enter input string: ")

words = str_words.split()
words.sort()
for word in words:
    print(word)

Enter input string: my name is harshal
harshal
is
my
name


In [56]:
def sortString():
    string = input("Enter a String: ").title()
    sorted_list = sorted(string.split(' '))
    print(' '.join(sorted_list))

sortString()

Enter a String: my name is harshal
Harshal Is My Name


<b> Question No. 5<b> :-  Write a Python Program to Remove Punctuation From a String?

In [58]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuations"My name is @Harshal"
My name is Harshal
